version: "3"

services:
  api:
    build: .
    # environment:
    #   ELASTICSEARCH_URL: http://elasticsearch.codeformuenster.org
    volumes:
    - .:/usr/src/app

  elasticsearch:
    # image: elasticsearch:5.3
    # image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
